"""initial_schema

Revision ID: b4f97bd5883c
Revises: 
Create Date: 2026-09-20 02:26:36.361456
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = 'b4f97bd5883c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('objecttype',
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('readiness', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('robotsolution',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('manufacturer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('catalog_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('subtype', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('process', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('trl', sa.Integer(), nullable=True),
    sa.Column('market_potential', sa.Float(), nullable=True),
    sa.Column('region', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('industry', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('price_rub', sa.Float(), nullable=True),
    sa.Column('max_payload_kg', sa.Float(), nullable=True),
    sa.Column('data_completeness', sa.Float(), nullable=False),
    sa.Column('source_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_robotsolution_catalog_type'), 'robotsolution', ['catalog_type'], unique=False)
    op.create_index(op.f('ix_robotsolution_industry'), 'robotsolution', ['industry'], unique=False)
    op.create_index(op.f('ix_robotsolution_manufacturer'), 'robotsolution', ['manufacturer'], unique=False)
    op.create_index(op.f('ix_robotsolution_name'), 'robotsolution', ['name'], unique=False)
    op.create_index(op.f('ix_robotsolution_process'), 'robotsolution', ['process'], unique=False)
    op.create_index(op.f('ix_robotsolution_status'), 'robotsolution', ['status'], unique=False)
    op.create_table('sourceevidence',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=320), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_role'), 'user', ['role'], unique=False)
    op.create_table('auditevent',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('actor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditevent_action'), 'auditevent', ['action'], unique=False)
    op.create_table('deploymentcase',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('solution_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('source_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['solution_id'], ['robotsolution.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deploymentcase_solution_id'), 'deploymentcase', ['solution_id'], unique=False)
    op.create_table('objectparameterdefinition',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('object_type_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('section', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('baseline', sa.JSON(), nullable=True),
    sa.Column('minimum', sa.Float(), nullable=True),
    sa.Column('maximum', sa.Float(), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('value_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('source_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['object_type_code'], ['objecttype.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_type_code', 'code')
    )
    op.create_index(op.f('ix_objectparameterdefinition_code'), 'objectparameterdefinition', ['code'], unique=False)
    op.create_index(op.f('ix_objectparameterdefinition_object_type_code'), 'objectparameterdefinition', ['object_type_code'], unique=False)
    op.create_table('project',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('object_type_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('calculation_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['object_type_code'], ['objecttype.code'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_owner_id'), 'project', ['owner_id'], unique=False)
    op.create_table('economicscenario',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scenario_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_economicscenario_project_id'), 'economicscenario', ['project_id'], unique=False)
    op.create_table('matchingrun',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('input_snapshot', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matchingrun_project_id'), 'matchingrun', ['project_id'], unique=False)
    op.create_table('projectparametervalue',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('definition_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('original_value', sa.JSON(), nullable=True),
    sa.Column('source_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('changed_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'definition_code')
    )
    op.create_index(op.f('ix_projectparametervalue_definition_code'), 'projectparametervalue', ['definition_code'], unique=False)
    op.create_index(op.f('ix_projectparametervalue_project_id'), 'projectparametervalue', ['project_id'], unique=False)
    op.create_table('economicassumption',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scenario_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('original_value', sa.JSON(), nullable=True),
    sa.Column('current_value', sa.JSON(), nullable=True),
    sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('changed_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['economicscenario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_economicassumption_scenario_id'), 'economicassumption', ['scenario_id'], unique=False)
    op.create_table('economicresult',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scenario_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['economicscenario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_economicresult_scenario_id'), 'economicresult', ['scenario_id'], unique=False)
    op.create_table('matchingcandidate',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('matching_run_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('solution_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('eligible', sa.Boolean(), nullable=False),
    sa.Column('explanation', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['matching_run_id'], ['matchingrun.id'], ),
    sa.ForeignKeyConstraint(['solution_id'], ['robotsolution.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matchingcandidate_matching_run_id'), 'matchingcandidate', ['matching_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matchingcandidate_matching_run_id'), table_name='matchingcandidate')
    op.drop_table('matchingcandidate')
    op.drop_index(op.f('ix_economicresult_scenario_id'), table_name='economicresult')
    op.drop_table('economicresult')
    op.drop_index(op.f('ix_economicassumption_scenario_id'), table_name='economicassumption')
    op.drop_table('economicassumption')
    op.drop_index(op.f('ix_projectparametervalue_project_id'), table_name='projectparametervalue')
    op.drop_index(op.f('ix_projectparametervalue_definition_code'), table_name='projectparametervalue')
    op.drop_table('projectparametervalue')
    op.drop_index(op.f('ix_matchingrun_project_id'), table_name='matchingrun')
    op.drop_table('matchingrun')
    op.drop_index(op.f('ix_economicscenario_project_id'), table_name='economicscenario')
    op.drop_table('economicscenario')
    op.drop_index(op.f('ix_project_owner_id'), table_name='project')
    op.drop_table('project')
    op.drop_index(op.f('ix_objectparameterdefinition_object_type_code'), table_name='objectparameterdefinition')
    op.drop_index(op.f('ix_objectparameterdefinition_code'), table_name='objectparameterdefinition')
    op.drop_table('objectparameterdefinition')
    op.drop_index(op.f('ix_deploymentcase_solution_id'), table_name='deploymentcase')
    op.drop_table('deploymentcase')
    op.drop_index(op.f('ix_auditevent_action'), table_name='auditevent')
    op.drop_table('auditevent')
    op.drop_index(op.f('ix_user_role'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('sourceevidence')
    op.drop_index(op.f('ix_robotsolution_status'), table_name='robotsolution')
    op.drop_index(op.f('ix_robotsolution_process'), table_name='robotsolution')
    op.drop_index(op.f('ix_robotsolution_name'), table_name='robotsolution')
    op.drop_index(op.f('ix_robotsolution_manufacturer'), table_name='robotsolution')
    op.drop_index(op.f('ix_robotsolution_industry'), table_name='robotsolution')
    op.drop_index(op.f('ix_robotsolution_catalog_type'), table_name='robotsolution')
    op.drop_table('robotsolution')
    op.drop_table('objecttype')
    # ### end Alembic commands ###
